import { 
  WafRule, 
  ZeroTrustPolicy, 
  DsarRequest, 
  ConsentRecord,
  ComplianceFramework, 
  AlertIncident, 
  IntegrationConnector,
  SecurityFinding,
  ProtectedAsset,
  InventoryAsset,
  EnclaveActivityEvent
} from '../types';

export const initialSecurityFindings: SecurityFinding[] = [
  {
    id: 'FIND-001',
    title: 'Outdated TLS 1.2 Cipher Suites Permitted on Ingress Edge #03',
    category: 'WAF & Perimeter',
    severity: 'high',
    scoreImpact: 6,
    status: 'open',
    resource: 'Edge Gateway Frankfurt (ingress-eu-central-03)',
    description: 'CBC-mode cipher suites detected on secondary public endpoint. SkyGuard recommends enforcing strict TLS 1.3 with ChaCha20-Poly1305 / AES-GCM.',
    remediation: 'Disable legacy TLS 1.2 fallback in Gateway Security Profile #18.',
    discoveredAt: '18 mins ago'
  },
  {
    id: 'FIND-002',
    title: 'Overprivileged IAM Service Account in Telemetry Collector',
    category: 'Zero-Trust Auth',
    severity: 'medium',
    scoreImpact: 4,
    status: 'open',
    resource: 'Service Account: svc-telemetry-worker@sovereign-mesh',
    description: 'Service account has standing permissions across KMS Partition #01 rather than ephemeral Just-In-Time (JIT) 15-minute token leases.',
    remediation: 'Attach Zero-Trust Policy ZT-POL-04 to mandate ephemeral token leases.',
    discoveredAt: '1 hour ago'
  },
  {
    id: 'FIND-003',
    title: 'Unencrypted S3/GCS Enclave Snapshot Backup in Stage Zone',
    category: 'Data Protection',
    severity: 'medium',
    scoreImpact: 3,
    status: 'mitigating',
    resource: 'Bucket: sovereign-vault-stage-backup-eu',
    description: 'Bucket default encryption relies on provider-managed keys instead of customer-controlled HSM Envelope Key #54.',
    remediation: 'Apply AES-256-GCM Customer Managed Key (CMK) policy to storage bucket.',
    discoveredAt: '3 hours ago'
  },
  {
    id: 'FIND-004',
    title: 'Suboptimal Rate-Limit Granularity on Webhook Endpoint',
    category: 'Configuration',
    severity: 'low',
    scoreImpact: 0,
    status: 'resolved',
    resource: 'API Endpoint: /api/v2/webhooks/incoming',
    description: 'Sliding window rate limit was set to 500 req/min instead of adaptive per-IP 100 req/min threshold.',
    remediation: 'Applied adaptive token-bucket algorithm via WAF Rule #02.',
    discoveredAt: 'Yesterday'
  }
];

export const initialProtectedAssets: ProtectedAsset[] = [
  { id: 'AST-01', name: 'Primary Sovereign Kubernetes Cluster (EKS)', type: 'Kubernetes Cluster', region: 'eu-central-1', securityScore: 94, status: 'protected', enclaveId: 'enc-k8s-prod-01', lastHardened: 'Today, 04:00', vulnerabilitiesCount: 0 },
  { id: 'AST-02', name: 'Global API Gateway & Ingress Mesh', type: 'API Gateway', region: 'Global Edge (280 PoPs)', securityScore: 88, status: 'warning', enclaveId: 'enc-edge-gw-01', lastHardened: 'Today, 05:12', vulnerabilitiesCount: 1 },
  { id: 'AST-03', name: 'Customer PII Vault & Tokenizer Enclave', type: 'Postgres DB Enclave', region: 'il-central-1', securityScore: 99, status: 'protected', enclaveId: 'enc-db-pii-04', lastHardened: 'Yesterday', vulnerabilitiesCount: 0 },
  { id: 'AST-04', name: 'Hardware Security Module (HSM) Key Vault', type: 'KMS Partition', region: 'eu-west-1', securityScore: 100, status: 'protected', enclaveId: 'enc-kms-hsm-02', lastHardened: 'Today, 02:00', vulnerabilitiesCount: 0 },
  { id: 'AST-05', name: 'Secondary Kubernetes Workload Cluster', type: 'Kubernetes Cluster', region: 'us-east-1', securityScore: 91, status: 'protected', enclaveId: 'enc-k8s-us-02', lastHardened: 'Today, 01:30', vulnerabilitiesCount: 0 },
  { id: 'AST-06', name: 'Micro-segmentation Zero-Trust Ingress Proxy', type: 'Zero-Trust Ingress', region: 'Global Edge', securityScore: 96, status: 'protected', enclaveId: 'enc-zt-proxy-01', lastHardened: 'Today, 03:00', vulnerabilitiesCount: 0 },
  { id: 'AST-07', name: 'Encrypted Redis Session Cluster (In-Memory)', type: 'Redis Cache', region: 'eu-central-1', securityScore: 95, status: 'protected', enclaveId: 'enc-redis-sess-01', lastHardened: '3 days ago', vulnerabilitiesCount: 0 },
  { id: 'AST-08', name: 'Sovereign Blob & Artifacts Vault', type: 'Storage Bucket', region: 'eu-west-3', securityScore: 89, status: 'warning', enclaveId: 'enc-s3-sovereign-01', lastHardened: 'Yesterday', vulnerabilitiesCount: 1 },
  { id: 'AST-09', name: 'Auth & SAML/OIDC Identity Provider Gateway', type: 'API Gateway', region: 'Global Edge', securityScore: 98, status: 'protected', enclaveId: 'enc-idp-gw-01', lastHardened: 'Today, 04:30', vulnerabilitiesCount: 0 },
  { id: 'AST-10', name: 'Financial Transaction Ledger Enclave', type: 'Postgres DB Enclave', region: 'eu-central-1', securityScore: 99, status: 'protected', enclaveId: 'enc-db-ledger-01', lastHardened: 'Today, 00:00', vulnerabilitiesCount: 0 },
  { id: 'AST-11', name: 'SIEM Log Buffer & Kafka Pipeline', type: 'Kubernetes Cluster', region: 'eu-central-1', securityScore: 92, status: 'protected', enclaveId: 'enc-kafka-siem-01', lastHardened: 'Yesterday', vulnerabilitiesCount: 0 },
  { id: 'AST-12', name: 'Real-Time Threat Intelligence Cache', type: 'Redis Cache', region: 'Global Edge', securityScore: 97, status: 'protected', enclaveId: 'enc-redis-threat-01', lastHardened: 'Today, 05:00', vulnerabilitiesCount: 0 },
  { id: 'AST-13', name: 'Post-Quantum TLS Certificate Store', type: 'KMS Partition', region: 'il-central-1', securityScore: 100, status: 'protected', enclaveId: 'enc-kms-pqc-01', lastHardened: 'Today, 02:15', vulnerabilitiesCount: 0 },
  { id: 'AST-14', name: 'External Webhook Ingress Gateway', type: 'API Gateway', region: 'us-west-2', securityScore: 84, status: 'warning', enclaveId: 'enc-gw-webhook-02', lastHardened: '2 days ago', vulnerabilitiesCount: 1 },
  { id: 'AST-15', name: 'Continuous Evidence Storage Bucket', type: 'Storage Bucket', region: 'eu-central-1', securityScore: 98, status: 'protected', enclaveId: 'enc-s3-evidence-01', lastHardened: 'Yesterday', vulnerabilitiesCount: 0 },
  { id: 'AST-16', name: 'Machine Learning Anomaly Detection Pods', type: 'Kubernetes Cluster', region: 'us-east-1', securityScore: 94, status: 'protected', enclaveId: 'enc-k8s-ai-01', lastHardened: 'Today, 03:45', vulnerabilitiesCount: 0 },
  { id: 'AST-17', name: 'Immutable Audit Trail DB Enclave', type: 'Postgres DB Enclave', region: 'eu-west-1', securityScore: 100, status: 'protected', enclaveId: 'enc-db-audit-01', lastHardened: 'Today, 01:00', vulnerabilitiesCount: 0 },
  { id: 'AST-18', name: 'Zero-Trust Internal Bastion Host', type: 'Zero-Trust Ingress', region: 'eu-central-1', securityScore: 96, status: 'protected', enclaveId: 'enc-zt-bastion-01', lastHardened: 'Today, 04:10', vulnerabilitiesCount: 0 },
  { id: 'AST-19', name: 'Distributed Rate-Limiter Cache Mesh', type: 'Redis Cache', region: 'Global Edge', securityScore: 97, status: 'protected', enclaveId: 'enc-redis-rate-01', lastHardened: 'Today, 05:30', vulnerabilitiesCount: 0 },
  { id: 'AST-20', name: 'DSAR Cryptographic Shredding Workspace', type: 'Postgres DB Enclave', region: 'eu-central-1', securityScore: 99, status: 'protected', enclaveId: 'enc-db-dsar-01', lastHardened: 'Yesterday', vulnerabilitiesCount: 0 },
  { id: 'AST-21', name: 'Cloud Perimeter DDoS Scrubbing Hub', type: 'API Gateway', region: 'Global Edge', securityScore: 95, status: 'protected', enclaveId: 'enc-scrubber-01', lastHardened: 'Today, 05:40', vulnerabilitiesCount: 0 },
  { id: 'AST-22', name: 'Sovereign White-Label Custom Domain CDN', type: 'Zero-Trust Ingress', region: 'Global Edge', securityScore: 94, status: 'protected', enclaveId: 'enc-cdn-wl-01', lastHardened: 'Yesterday', vulnerabilitiesCount: 0 },
  { id: 'AST-23', name: 'Ephemeral Sandbox Execution Nodes', type: 'Kubernetes Cluster', region: 'eu-west-1', securityScore: 93, status: 'protected', enclaveId: 'enc-k8s-sandbox-01', lastHardened: 'Today, 02:40', vulnerabilitiesCount: 0 },
  { id: 'AST-24', name: 'Disaster Recovery Warm Backup Enclave', type: 'Storage Bucket', region: 'il-central-1', securityScore: 98, status: 'protected', enclaveId: 'enc-s3-dr-01', lastHardened: 'Today, 00:30', vulnerabilitiesCount: 0 },
];


export const initialWafRules: WafRule[] = [
  {
    id: 'waf_rule_01',
    name: 'OWASP Top 10 Core Rule Set (CRS 4.0)',
    type: 'sql_injection',
    status: 'active',
    action: 'block',
    matchedLast24h: 14820,
    updatedAt: '2026-08-20T04:12:00Z',
    severity: 'critical',
  },
  {
    id: 'waf_rule_02',
    name: 'Adaptive L7 DDoS Rate-Limiting Enclave',
    type: 'rate_limiting',
    status: 'active',
    action: 'challenge',
    matchedLast24h: 89400,
    updatedAt: '2026-08-20T05:00:00Z',
    severity: 'high',
  },
  {
    id: 'waf_rule_03',
    name: 'Anomalous Botnet & Scraper Shield',
    type: 'bot_challenge',
    status: 'active',
    action: 'challenge',
    matchedLast24h: 32410,
    updatedAt: '2026-08-19T22:30:00Z',
    severity: 'medium',
  },
  {
    id: 'waf_rule_04',
    name: 'Zero-Day Polymorphic XSS Mitigator',
    type: 'xss_shield',
    status: 'active',
    action: 'block',
    matchedLast24h: 4210,
    updatedAt: '2026-08-20T03:15:00Z',
    severity: 'high',
  },
  {
    id: 'waf_rule_05',
    name: 'Sanctioned Sovereign Geofence Filter',
    type: 'geo_fencing',
    status: 'active',
    action: 'block',
    matchedLast24h: 7610,
    updatedAt: '2026-08-18T18:00:00Z',
    severity: 'high',
  },
];

export const initialZeroTrustPolicies: ZeroTrustPolicy[] = [
  {
    id: 'zt_pol_01',
    name: 'Production Kubernetes Cluster Core API',
    enclave: 'eu-central-sovereign-01',
    postureRequirement: 'Hardware TPM 2.0 + YubiKey FIDO2 Binding',
    deviceTrust: 'Hardware Root of Trust',
    activeSessions: 42,
    status: 'enforced',
  },
  {
    id: 'zt_pol_02',
    name: 'Customer PII Vault & Database Micro-segment',
    enclave: 'il-telaviv-vault-04',
    postureRequirement: 'Zero-Standing-Privilege (JIT 15-min grant)',
    deviceTrust: 'Managed',
    activeSessions: 7,
    status: 'enforced',
  },
  {
    id: 'zt_pol_03',
    name: 'Telemetry Ingestion Pipeline & SIEM Stream',
    enclave: 'global-mesh-edge',
    postureRequirement: 'mTLS v1.3 with Ephemeral Ed25519 Certs',
    deviceTrust: 'Biometric Bound',
    activeSessions: 1840,
    status: 'enforced',
  },
];

export const initialDsarRequests: DsarRequest[] = [
  {
    id: 'DSAR-2026-891',
    subjectName: 'Alexander Vance',
    subjectEmail: 'a.vance@enterprise-eu.com',
    type: 'Right to Erasure (Shred)',
    regulation: 'GDPR Art. 17',
    status: 'crypto_shredding',
    submittedAt: '2026-08-19T14:20:00Z',
    deadlineDays: 28,
  },
  {
    id: 'DSAR-2026-892',
    subjectName: 'Elena Rostova',
    subjectEmail: 'elena.rostova@privacy-org.de',
    type: 'Right to Access',
    regulation: 'GDPR Art. 17',
    status: 'verifying_id',
    submittedAt: '2026-08-20T01:10:00Z',
    deadlineDays: 30,
  },
  {
    id: 'DSAR-2026-893',
    subjectName: 'Jonathan Davis',
    subjectEmail: 'jdavis@california-corp.us',
    type: 'Portability',
    regulation: 'CCPA § 1798.105',
    status: 'completed',
    submittedAt: '2026-08-18T09:45:00Z',
    deadlineDays: 42,
  },
  {
    id: 'DSAR-2026-894',
    subjectName: 'Miriam Al-Mansoor',
    subjectEmail: 'm.mansoor@gulf-fintech.ae',
    type: 'Consent Revocation',
    regulation: 'GDPR Art. 17',
    status: 'pending',
    submittedAt: '2026-08-20T03:50:00Z',
    deadlineDays: 29,
  },
  {
    id: 'DSAR-2026-895',
    subjectName: 'Chen Wei',
    subjectEmail: 'chen.wei@singapore-sec.sg',
    type: 'Right to Access',
    regulation: 'PIPEDA',
    status: 'verifying_id',
    submittedAt: '2026-08-19T22:15:00Z',
    deadlineDays: 35,
  },
];

export const initialConsentRecords: ConsentRecord[] = [
  {
    id: 'REC-CSNT-88101',
    subjectEmail: 'sarah.connor@cybertech.eu',
    subjectId: 'usr_8810192',
    purposes: ['Essential Cookies', 'Telemetry Analytics', 'Security Diagnostics'],
    status: 'active',
    source: 'Web Cookie Banner',
    timestamp: '2026-08-20T04:15:22.481Z',
    legalBasis: 'Explicit Consent (GDPR Art. 6(1)(a))',
    ipAddress: '194.26.29.110 (Frankfurt, DE)',
    signatureHash: '0x8f2a91b0c948e71b2d4f5e6a987c3b2104fae19b8827e8a91c7f543201dce90a'
  },
  {
    id: 'REC-CSNT-88102',
    subjectEmail: 'marcus.aurelius@rome-sec.it',
    subjectId: 'usr_7729104',
    purposes: ['Essential Cookies', 'Personalized Experience', 'Marketing Opt-In'],
    status: 'active',
    source: 'Signup Form',
    timestamp: '2026-08-19T21:40:11.902Z',
    legalBasis: 'Explicit Consent (GDPR Art. 6(1)(a))',
    ipAddress: '82.112.44.89 (Rome, IT)',
    signatureHash: '0x4e7c109ad5813e2f9801acdb827104928172901fabced3849102837461928374'
  },
  {
    id: 'REC-CSNT-88103',
    subjectEmail: 'a.vance@enterprise-eu.com',
    subjectId: 'usr_9918231',
    purposes: ['Essential Cookies', 'Marketing Opt-In'],
    status: 'withdrawn',
    source: 'Terms of Service Checkbox',
    timestamp: '2026-08-19T14:22:00.110Z',
    legalBasis: 'Withdrawn via Right to Erasure',
    ipAddress: '185.12.88.42 (Paris, FR)',
    signatureHash: '0x1029384756abcdef0192837465fabcde10293847561029384756abcdef019283'
  },
  {
    id: 'REC-CSNT-88104',
    subjectEmail: 'dev.lead@cloudsovereign.io',
    subjectId: 'usr_5548190',
    purposes: ['Essential Cookies', 'Telemetry Analytics', 'Profiling & AI Training'],
    status: 'active',
    source: 'OAuth Gateway',
    timestamp: '2026-08-18T18:05:44.220Z',
    legalBasis: 'Explicit Consent (GDPR Art. 6(1)(a))',
    ipAddress: '212.58.244.70 (London, UK)',
    signatureHash: '0xabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789'
  }
];

export const privacyFeatures = [
  {
    id: "gdpr-consent",
    title: "GDPR Consent Bundle",
    category: "privacy",
    description: "Create and manage consent records.",
    route: "/dashboard/privacy/consent",
    plan: "pro",
    status: "planned",
    capabilities: [
      "Create consent record",
      "Record timestamp",
      "Record consent source",
      "Export consent history",
      "Withdraw consent"
    ]
  }
];

export const initialFrameworks: ComplianceFramework[] = [
  {
    id: 'soc2_type2',
    name: 'SOC 2 Type II',
    version: '2026 Trust Services Criteria',
    overallScore: 94.0,
    totalControls: 50,
    passedControls: 47,
    failingControls: 0,
    inProgressControls: 3,
    lastAudited: '2026-08-20T04:00:00Z',
    controls: [
      { id: 'CC6.1', title: 'Logical Access Controls & Perimeter Protection', category: 'Security', status: 'passed', evidenceId: 'EVD-SOC-991', linkedFeatureId: 31 },
      { id: 'CC6.6', title: 'Boundary Defense & Micro-segmentation', category: 'Security', status: 'passed', evidenceId: 'EVD-SOC-992', linkedFeatureId: 27 },
      { id: 'CC7.2', title: 'Real-time Security Telemetry & Anomaly Ingestion', category: 'Monitoring', status: 'passed', evidenceId: 'EVD-SOC-993', linkedFeatureId: 67 },
      { id: 'CC8.1', title: 'Change Authorization & Enclave Signed GitOps', category: 'Operations', status: 'warning', evidenceId: 'EVD-SOC-994', linkedFeatureId: 19 },
    ],
  },
  {
    id: 'iso_27001',
    name: 'ISO/IEC 27001:2022',
    version: 'Information Security Management',
    overallScore: 96.0,
    totalControls: 40,
    passedControls: 38,
    failingControls: 0,
    inProgressControls: 2,
    lastAudited: '2026-08-19T21:30:00Z',
    controls: [
      { id: 'A.8.20', title: 'Network Security & Sovereign Data Sharding', category: 'Technological', status: 'passed', evidenceId: 'EVD-ISO-820', linkedFeatureId: 54 },
      { id: 'A.8.24', title: 'Use of Cryptography & Post-Quantum Algorithms', category: 'Cryptographic', status: 'passed', evidenceId: 'EVD-ISO-824', linkedFeatureId: 53 },
      { id: 'A.5.15', title: 'Access Control & Hardware Bound Auth', category: 'Organizational', status: 'passed', evidenceId: 'EVD-ISO-515', linkedFeatureId: 40 },
    ],
  },
  {
    id: 'hipaa_security',
    name: 'HIPAA Security Rule',
    version: '45 CFR Part 160 & Part 164',
    overallScore: 88.0,
    totalControls: 35,
    passedControls: 31,
    failingControls: 1,
    inProgressControls: 3,
    lastAudited: '2026-08-20T02:15:00Z',
    controls: [
      { id: '164.312(a)(1)', title: 'Access Control & Unique User Identification', category: 'Technical Safeguards', status: 'passed', evidenceId: 'EVD-HIP-101', linkedFeatureId: 43 },
      { id: '164.312(a)(2)(iv)', title: 'Automatic Logoff & Cryptographic Quarantine', category: 'Technical Safeguards', status: 'passed', evidenceId: 'EVD-HIP-102', linkedFeatureId: 44 },
      { id: '164.312(e)(1)', title: 'Transmission Security & Zero-Leak Tunneling', category: 'Transmission', status: 'passed', evidenceId: 'EVD-HIP-103', linkedFeatureId: 55 },
    ],
  },
  {
    id: 'gdpr_privacy',
    name: 'GDPR / CPRA Privacy Framework',
    version: 'Regulation (EU) 2016/679',
    overallScore: 90.0,
    totalControls: 25,
    passedControls: 22,
    failingControls: 0,
    inProgressControls: 3,
    lastAudited: '2026-08-20T05:00:00Z',
    controls: [
      { id: 'Art. 25', title: 'Data Protection by Design & Default', category: 'Architecture', status: 'passed', evidenceId: 'EVD-GDP-025', linkedFeatureId: 1 },
      { id: 'Art. 17', title: 'Right to Erasure with Cryptographic Shredding', category: 'Subject Rights', status: 'passed', evidenceId: 'EVD-GDP-017', linkedFeatureId: 4 },
      { id: 'Art. 32', title: 'Security of Processing & Pseudonymization', category: 'Security', status: 'passed', evidenceId: 'EVD-GDP-032', linkedFeatureId: 8 },
    ],
  },
];

export const initialAlerts: AlertIncident[] = [
  {
    id: 'alert_123',
    title: 'Repeated failed login attempts',
    severity: 'high',
    status: 'new',
    source: 'authentication',
    createdAt: '2026-08-20T06:18:22Z',
    affectedAsset: 'api.skyguard.com',
    assignedTo: null,
    target: 'api.skyguard.com',
    timestamp: '2 mins ago',
    description: 'Multiple consecutive failed authentication challenges detected from high-velocity origin IP targeting admin endpoints.',
    mitigationSteps: [
      'Trigger adaptive biometric MFA step-up challenge',
      'Temporarily rate-limit origin IP block in WAF',
      'Issue security notification email to affected user account'
    ],
    evidenceDigest: 'sha256:91b4028fa1029c...88ef2',
  },
  {
    id: 'alert_124',
    title: 'Distributed Credential Stuffing Surge Detected',
    severity: 'critical',
    status: 'new',
    source: 'bot_shield',
    createdAt: '2026-08-20T06:12:00Z',
    affectedAsset: 'auth.skyguard.com',
    assignedTo: null,
    target: '/api/v1/auth/token-exchange',
    timestamp: '8 mins ago',
    description: '14,200 requests originating from malicious ASN 4812 targeting OAuth token endpoints across 4 regions.',
    mitigationSteps: [
      'Activated Proof-of-Work cryptographic challenge',
      'Rate-limited ASN 4812 to 0 req/sec',
      'Quarantined 18 suspicious session tokens',
    ],
    evidenceDigest: 'sha256:88a7b9c091d84e...c1889',
  },
  {
    id: 'alert_125',
    title: 'Anomalous Zero-Day SQL Injection Sequence in Gateway',
    severity: 'high',
    status: 'investigating',
    source: 'waf_engine',
    createdAt: '2026-08-20T05:58:00Z',
    affectedAsset: 'gateway-eu-01.skyguard.com',
    assignedTo: 'Security Analyst Team',
    target: '/api/v2/tenants/query-metadata',
    timestamp: '22 mins ago',
    description: 'Hex-encoded blind boolean payload intercepted by SkyGuard Set 3 WAF core engine.',
    mitigationSteps: [
      'Packet blocked at edge (HTTP 403 Forbidden)',
      'Origin IP added to global blacklist mesh',
      'Captured full PCAP dump for forensic analysis',
    ],
    evidenceDigest: 'sha256:12c4d9a883e01f...8821a',
  },
  {
    id: 'alert_126',
    title: 'Unauthorized Privilege Escalation Probe on KMS Enclave',
    severity: 'high',
    status: 'investigating',
    source: 'zero_trust_guard',
    createdAt: '2026-08-20T05:40:00Z',
    affectedAsset: 'kms-hsm.skyguard.com',
    assignedTo: 'KMS Admin Enclave',
    target: 'KMS HSM Partition #02',
    timestamp: '40 mins ago',
    description: 'Service account tried to access root KMS encryption keys without JIT approval ticket.',
    mitigationSteps: [
      'Revoked pod mTLS certificate immediately',
      'Triggered automated workload isolation',
      'Logged forensic incident to Splunk & Datadog',
    ],
    evidenceDigest: 'sha256:77f10a8819d44c...991ab',
  },
  {
    id: 'alert_127',
    title: 'High-Volume Port Sweep on Sovereign Gateway',
    severity: 'medium',
    status: 'resolved',
    source: 'network_perimeter',
    createdAt: '2026-08-20T03:15:00Z',
    affectedAsset: 'lb-edge-01.skyguard.com',
    assignedTo: 'Automated DDoS Scrubber',
    target: 'Edge Load Balancer #01',
    timestamp: '3 hours ago',
    description: 'Rapid TCP SYN sweep across non-standard ports 8000-9000 mitigated at BGP edge.',
    mitigationSteps: [
      'Blackholed at BGP level',
      'Zero packets reached backend VPC',
    ],
    evidenceDigest: 'sha256:33d8819001bcae...55102',
  },
  {
    id: 'alert_128',
    title: 'Unusual Geo-IP Velocity on Admin Session',
    severity: 'low',
    status: 'resolved',
    source: 'session_manager',
    createdAt: '2026-08-20T01:00:00Z',
    affectedAsset: 'console.skyguard.com',
    assignedTo: 'Risk-Based Auth Agent',
    target: '/app/security',
    timestamp: '5 hours ago',
    description: 'Admin session authenticated from Frankfurt and 4 minutes later from Singapore.',
    mitigationSteps: [
      'Enforced biometric FIDO2 step-up challenge',
      'Terminated suspicious concurrent session',
    ],
    evidenceDigest: 'sha256:44e9910022fa1a...00921',
  },
];

export function getSystemHealth() {
  return {
    status: 'healthy',
    timestamp: '2026-08-20T12:00:00Z',
    services: {
      database: 'healthy',
      api: 'healthy',
      authentication: 'healthy',
    },
  };
}

export const mockSecurityEvents: Array<{
  id: string;
  timestamp: string;
  ip: string;
  country: string;
  attackType: string;
  actionTaken: string;
  featureId: number;
  featureName: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
}> = [
  {
    id: 'evt_9918',
    timestamp: 'Just now',
    ip: '194.26.29.14',
    country: 'RU',
    attackType: 'SQLi Obfuscated Payload on /api/v1/auth',
    actionTaken: 'BLOCKED',
    featureId: 27,
    featureName: 'Intelligent Next-Gen WAF',
    severity: 'high'
  },
  {
    id: 'evt_9917',
    timestamp: '3s ago',
    ip: '45.154.255.89',
    country: 'NL',
    attackType: 'HTTP/2 Rapid Reset Flooding (120k req/s)',
    actionTaken: 'MITIGATED',
    featureId: 28,
    featureName: 'Multi-Layer L3/L4/L7 DDoS Defense',
    severity: 'critical'
  },
  {
    id: 'evt_9916',
    timestamp: '8s ago',
    ip: '185.220.101.4',
    country: 'DE (Tor)',
    attackType: 'Credential Stuffing Bot Attack',
    actionTaken: 'BLOCKED',
    featureId: 29,
    featureName: 'Behavioral Bot Management',
    severity: 'medium'
  },
  {
    id: 'evt_9915',
    timestamp: '14s ago',
    ip: '82.102.23.110',
    country: 'IL',
    attackType: 'Outbound Unmasked Credit Card PII',
    actionTaken: 'TOKENIZED',
    featureId: 54,
    featureName: 'Real-Time PII & Financial Masking',
    severity: 'high'
  }
];

export const initialIntegrations: IntegrationConnector[] = [
  {
    id: 'splunk_enterprise',
    name: 'Splunk Cloud / Enterprise',
    category: 'SIEM & SOC',
    icon: 'Terminal',
    status: 'connected',
    lastSync: 'Real-time (3s ago)',
    eventsIngestedToday: 1842900,
    description: 'High-throughput HEC streaming of all 78 module telemetry logs with CEF/LEEF parsing.',
  },
  {
    id: 'crowdstrike_falcon',
    name: 'CrowdStrike Falcon Insight',
    category: 'SIEM & SOC',
    icon: 'Shield',
    status: 'connected',
    lastSync: 'Real-time (12s ago)',
    eventsIngestedToday: 412000,
    description: 'Bi-directional endpoint telemetry integration & automated network host containment.',
  },
  {
    id: 'aws_guardduty',
    name: 'AWS GuardDuty & Security Hub',
    category: 'Cloud Perimeter',
    icon: 'Cloud',
    status: 'connected',
    lastSync: '1 min ago',
    eventsIngestedToday: 890400,
    description: 'Continuous VPC flow logs, DNS anomalies, and IAM privilege drift monitoring.',
  },
  {
    id: 'datadog_security',
    name: 'Datadog Cloud SIEM',
    category: 'SIEM & SOC',
    icon: 'Activity',
    status: 'connected',
    lastSync: 'Real-time (5s ago)',
    eventsIngestedToday: 2150000,
    description: 'APM security tracing, runtime security signals, and CSPM compliance monitors.',
  },
  {
    id: 'okta_identity',
    name: 'Okta / Azure Entra ID',
    category: 'Identity Provider',
    icon: 'Key',
    status: 'connected',
    lastSync: '5 mins ago',
    eventsIngestedToday: 18400,
    description: 'SAML 2.0 / SCIM user provisioning, adaptive MFA enforcement, and risk-based session revocation.',
  },
  {
    id: 'slack_pagerduty',
    name: 'Slack & PagerDuty Ops',
    category: 'Incident Notification',
    icon: 'Bell',
    status: 'connected',
    lastSync: 'Real-time',
    eventsIngestedToday: 94,
    description: 'Instant notification webhooks for P1 Critical alarms and Slack interactive triage commands.',
  },
];

export const initialInventoryAssets: InventoryAsset[] = [
  // Websites
  {
    id: 'ast_web_01',
    name: 'Corporate Portal & Landing',
    category: 'Websites',
    identifier: 'https://mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '104.21.72.19 (Cloudflare Anycast Edge)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.8,
    lastScan: '3 mins ago',
    tags: ['Edge WAF', 'TLS 1.3 Strict', 'HSTS 2-Year', 'CSP Level 3'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_web_02',
    name: 'Enterprise Web Application',
    category: 'Websites',
    identifier: 'https://app.mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '172.67.180.44 (Shielded Ingress)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.4,
    lastScan: '1 min ago',
    tags: ['Zero-Trust', 'SAML 2.0', 'FIDO2 MFA', 'SOC 2 CC6.1'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_web_03',
    name: 'Developer API Documentation',
    category: 'Websites',
    identifier: 'https://docs.mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '198.41.214.162 (Edge CDN)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 98.6,
    lastScan: '15 mins ago',
    tags: ['Static Enclave', 'Rate Limited'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // APIs
  {
    id: 'ast_api_01',
    name: 'Core Production REST Gateway',
    category: 'APIs',
    identifier: 'https://api.mycompany.com/v1',
    parentApex: 'mycompany.com',
    status: 'monitoring',
    ipOrHost: '10.0.4.12 (mTLS Gateway Pod)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.1,
    lastScan: 'Real-time (Active)',
    tags: ['mTLS Enforced', 'JWT Validation', 'PII Masking', 'Rate Limit 10k/min'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_api_02',
    name: 'OAuth 2.0 & OIDC Identity Provider',
    category: 'APIs',
    identifier: 'https://auth.mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.4.88 (Auth Microservice)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: 'Real-time (Active)',
    tags: ['FIDO2 WebAuthn', 'KMS Key Rotation', 'Credential Stuffing Shield'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_api_03',
    name: 'Federated GraphQL Gateway',
    category: 'APIs',
    identifier: 'https://graphql.mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.5.21 (Apollo Enclave)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 97.9,
    lastScan: '5 mins ago',
    tags: ['Query Depth Limit', 'Field PII Tokenization'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // Domains
  {
    id: 'ast_dom_01',
    name: 'Apex Primary Domain',
    category: 'Domains',
    identifier: 'mycompany.com',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'DNSSEC Signed (Algorithm 13 ECDSAP256SHA256)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: '12 mins ago',
    tags: ['DNSSEC Enabled', 'CAA Records Enforced', 'Registrar Lock', 'BGP Anycast'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_dom_02',
    name: 'Developer Sandbox Domain',
    category: 'Domains',
    identifier: 'mycompany.io',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'DNSSEC Signed',
    environment: 'staging',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 96.5,
    lastScan: '25 mins ago',
    tags: ['Wildcard TLS', 'Isolated VPC'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_dom_03',
    name: 'Global Asset CDN Domain',
    category: 'Domains',
    identifier: 'mycompany-cdn.net',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'Edge Anycast 280+ PoPs',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.0,
    lastScan: '8 mins ago',
    tags: ['Immutable Origin', 'DDoS L7 Scrubber'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // Servers
  {
    id: 'ast_srv_01',
    name: 'Sovereign Reverse Proxy Nginx',
    category: 'Servers',
    identifier: 'srv-prod-edge-nginx-01',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.1.14 (VPC DMZ)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.5,
    lastScan: '2 mins ago',
    tags: ['SELinux Enforcing', 'Hardened Kernel', 'Zero SSH (SSM Only)'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_srv_02',
    name: 'K8s Worker Node Enclave US-East',
    category: 'Servers',
    identifier: 'k8s-worker-us-east-04',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.244.3.88 (Private Subnet)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 98.8,
    lastScan: '4 mins ago',
    tags: ['eBPF Falcon Sensor', 'Cilium CNI mTLS', 'Rootless Containers'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_srv_03',
    name: 'Hardware Security Module (HSM)',
    category: 'Servers',
    identifier: 'sec-vault-hsm-01',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.99.2 (Air-gapped Enclave)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: 'Real-time (Active)',
    tags: ['FIPS 140-3 Level 4', 'Tamper Evident', 'Quantum Resilient Keys'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // Cloud Accounts
  {
    id: 'ast_cld_01',
    name: 'AWS Production Mesh Account',
    category: 'Cloud Accounts',
    identifier: 'AWS Production (acc_89124401)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'AWS Organization Org-89021 (us-east-1 / us-west-2)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.2,
    lastScan: '6 mins ago',
    tags: ['AWS GuardDuty', 'IAM Least Privilege', 'KMS Multi-Region', 'CloudTrail Locked'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_cld_02',
    name: 'GCP Sovereign DC Account',
    category: 'Cloud Accounts',
    identifier: 'GCP Sovereign (proj_skyguard_prod)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'GCP Organization 41920 (europe-west3)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 98.9,
    lastScan: '10 mins ago',
    tags: ['Security Command Center', 'VPC Service Controls', 'Binary Authorization'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_cld_03',
    name: 'Azure FedRAMP Tenant',
    category: 'Cloud Accounts',
    identifier: 'Azure FedRAMP (sub_vault_fed)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'Azure Gov Tenant (usgov-virginia)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: '14 mins ago',
    tags: ['FedRAMP High', 'Microsoft Defender for Cloud', 'Key Vault HSM'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // Applications
  {
    id: 'ast_app_01',
    name: 'SkyGuard Web Client Enclave',
    category: 'Applications',
    identifier: 'SkyGuard Web Client (v4.12.0)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'SPA Client Enclave / React 18',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.8,
    lastScan: 'Continuous',
    tags: ['DOM Sanitization', 'Subresource Integrity (SRI)', 'Zero-Trust RBAC'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_app_02',
    name: 'SkyGuard iOS Sentinel Mobile',
    category: 'Applications',
    identifier: 'SkyGuard iOS Sentinel (v3.8.1)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'Secure Enclave Biometric Pinning',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.4,
    lastScan: 'Continuous',
    tags: ['Certificate Pinning', 'Jailbreak Detection', 'FaceID Hardware Auth'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_app_03',
    name: 'SkyGuard CLI Defense Daemon',
    category: 'Applications',
    identifier: 'SkyGuard CLI Daemon (v2.4.0)',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: 'Native Go Binary / Linux & Darwin',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: 'Continuous',
    tags: ['Cosign Signed', 'SLSA Level 3', 'Zero-Config mTLS'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },

  // Databases
  {
    id: 'ast_db_01',
    name: 'PostgreSQL Primary Enclave',
    category: 'Databases',
    identifier: 'db-pg-cluster-01.internal',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.12.5 (Encrypted at Rest KMS)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: 'Real-time (Active)',
    tags: ['KMS Envelope AES-256-GCM', 'Audit Query Logging', 'Automated Daily Proofs', 'SOC 2 Type II'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_db_02',
    name: 'Redis High-Velocity Session Cluster',
    category: 'Databases',
    identifier: 'redis-session-cluster.internal',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.12.18 (In-Memory Ephemeral)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 99.1,
    lastScan: 'Real-time (Active)',
    tags: ['TLS 1.3 In-Transit', 'Auto-Expiring JIT Tokens', 'Auth Requirepass'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
  {
    id: 'ast_db_03',
    name: 'KMS Sovereign Cryptographic Store',
    category: 'Databases',
    identifier: 'hsm-kms-root-partition-02',
    parentApex: 'mycompany.com',
    status: 'healthy',
    ipOrHost: '10.0.99.10 (Hardware Root of Trust)',
    environment: 'production',
    monitoringActive: true,
    compliancePassing: true,
    securityScore: 100.0,
    lastScan: 'Real-time (Active)',
    tags: ['FIPS 140-3', 'Zero Plaintext Keys', 'Dual-Custody Ceremony', 'Immutable Audit'],
    vulnerabilitiesCount: 0,
    wafShielded: true,
  },
];

export const initialEnclaveActivityEvents: EnclaveActivityEvent[] = [
  {
    id: 'EVT-2026-9081',
    type: 'user_login',
    title: 'User logged in',
    pillar: 'Monitoring',
    actor: 'sarah.connor@mycompany.com',
    actorRole: 'Security Officer',
    targetAsset: 'https://app.mycompany.com',
    timestamp: '1 min ago',
    details: 'SAML 2.0 SSO + FIDO2 WebAuthn biometric challenge passed from trusted corporate device enclave.',
    ipAddress: '192.88.99.14 (London DC)',
    evidenceDigest: 'sha256:88a109fe...c912a',
    status: 'success',
  },
  {
    id: 'EVT-2026-9082',
    type: 'password_change',
    title: 'User changed password',
    pillar: 'Security',
    actor: 'david.miller@mycompany.com',
    actorRole: 'Admin',
    targetAsset: 'https://auth.mycompany.com',
    timestamp: '4 mins ago',
    details: 'Password entropy validated (Score: 100/100). Sealed with KMS envelope key; all previous sessions invalidated.',
    ipAddress: '84.112.44.19 (Frankfurt DC)',
    evidenceDigest: 'sha256:12c4b810...bb201',
    status: 'success',
  },
  {
    id: 'EVT-2026-9083',
    type: 'api_key_create',
    title: 'User created API key',
    pillar: 'Security',
    actor: 'alex.chen@mycompany.com',
    actorRole: 'DevOps Lead',
    targetAsset: 'https://api.mycompany.com/v1',
    timestamp: '9 mins ago',
    details: 'Generated scoped read-only telemetry token (sk_live_sec_99a8b...) with 30-day automated key rotation.',
    ipAddress: '140.82.114.3 (Seattle)',
    evidenceDigest: 'sha256:77d90184...ff091',
    status: 'info',
  },
  {
    id: 'EVT-2026-9084',
    type: 'admin_role_change',
    title: 'Admin changed role',
    pillar: 'Compliance',
    actor: 'elena.rostova@mycompany.com (Owner)',
    actorRole: 'Owner',
    targetAsset: 'SkyGuard Web Client (v4.12.0)',
    timestamp: '15 mins ago',
    details: 'Promoted Marcus Vance from "viewer" to "security_analyst" following SOC 2 CC6.1 dual-signoff protocol.',
    ipAddress: '194.26.29.112 (Zurich)',
    evidenceDigest: 'sha256:44b19280...110a2',
    status: 'warning',
  },
  {
    id: 'EVT-2026-9085',
    type: 'consent_exported',
    title: 'Consent exported',
    pillar: 'Compliance',
    actor: 'clara.oswald@mycompany.com (Privacy Officer)',
    actorRole: 'Privacy Officer',
    targetAsset: 'PostgreSQL Primary Enclave',
    timestamp: '22 mins ago',
    details: 'Exported 14,280 GDPR Art. 7 consent ledger records with verifiable cryptographic Merkle tree audit proofs.',
    ipAddress: '51.15.22.84 (Paris)',
    evidenceDigest: 'sha256:99f8102a...e4401',
    status: 'success',
  },
  {
    id: 'EVT-2026-9086',
    type: 'privacy_request_completed',
    title: 'Privacy request completed',
    pillar: 'Compliance',
    actor: 'Automated DSAR Quarantine Engine',
    actorRole: 'System Agent',
    targetAsset: 'mycompany.com',
    timestamp: '35 mins ago',
    details: 'Executed GDPR Art. 17 Right to Erasure request [DSAR-2026-891] with zero-fill cryptographic shredding.',
    ipAddress: '10.0.12.5 (Enclave Internal)',
    evidenceDigest: 'sha256:33a01984...b9921',
    status: 'success',
  },
  {
    id: 'EVT-2026-9087',
    type: 'alert_resolved',
    title: 'Alert resolved',
    pillar: 'Security',
    actor: 'Security Analyst Team',
    actorRole: 'Security Analyst',
    targetAsset: 'api.skyguard.com',
    timestamp: '48 mins ago',
    details: 'Mitigated "Repeated failed login attempts" (alert_123) by enforcing origin IP quarantine in edge WAF mesh.',
    ipAddress: '10.0.4.12 (SOC Gateway)',
    evidenceDigest: 'sha256:91b4028f...88ef2',
    status: 'success',
  },
  {
    id: 'EVT-2026-9088',
    type: 'integration_connected',
    title: 'Integration connected',
    pillar: 'Monitoring',
    actor: 'DevOps Lead',
    actorRole: 'Admin',
    targetAsset: 'AWS Production Mesh Account',
    timestamp: '1 hour ago',
    details: 'Connected AWS GuardDuty VPC flow logs to SkyGuard SIEM pipeline; 890,400 events ingested today.',
    ipAddress: '10.0.1.14 (Proxy)',
    evidenceDigest: 'sha256:11a49901...33d19',
    status: 'info',
  },
];
